### ISSUE TITLE
Issue trying to use docker compose

### ISSUE THREAD

**Issue by tyvdh** [stellar/docker-stellar-core#58]
Trying to wrap this up into a clean docker-compose.yml file but running into an issue with a CLI depreciation. Odd that it works when running as two separate docker run commands.

Here's my docker-compose.yml

```yml
version: "2"

services:

  db_compat_complete_test:
    image: stellar/stellar-core-state:latest
    restart: always
    env_file:
      - ./examples/compat_complete.env
    volumes:
      - ./opt/data:/data
      - ./opt/postgresql:/var/lib/postgresql/data
    ports:
      - 5431:5432

  compat_complete_test:
    image: stellar/stellar-core:latest
    restart: always
    env_file:
      - ./examples/compat_complete.env
    volumes_from:
      - db_compat_complete_test:rw
    network_mode: "host"
    command: /start compat_complete_test fresh
    depends_on:
      - db_compat_complete_test
```

Everything fires up fine but gets caught in an error loop with this output

```sh
compat_complete_test_1     | Using DEPRECATED command-line syntax.
compat_complete_test_1     | Please refer to documentation for new syntax.
compat_complete_test_1     | 
compat_complete_test_1     | 2019-04-02T22:26:42.004 <startup> [default FATAL] Got an exception: Failed to parse 'stellar-core.cfg' :Failed to parse value type at line 1 [DeprecatedCommandLine.cpp:457]
docker-stellar-core_compat_complete_test_1 exited with code 1
```
