### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mymtw** [stellar/docker-stellar-core#70]
### What version are you using?
latest

### What did you do?

install stellar in test mode via docker

### What did you expect to see?
that it starting

### What did you see instead?
horizon_1   | 2020/05/26 23:50:15 --history-archive-urls must be set when --ingest is set
horizon                "./horizon --apply-m…"   22 minutes ago      Restarting (1) 19 seconds ago

example:
```
version: "3.1"

services:
  postgres:
    image: postgres:11.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - /data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    network_mode: '${NETWORK_MODE:-bridge}'

  core:
    # to use a specific version of stellar core
    # image: stellar/stellar-core:$VERSION
    image: stellar/stellar-core
    depends_on:
      - postgres
    restart: always
    ports:
      - "11625:11625"
      - "11626:11626"
    env_file:
      # to connect to the public stellar network
      # - ./stellar-core-pubnet.env
      - /my-project/path/stellar-core-testnet.env
    command: /start compat_minimal nopsql fresh
    network_mode: '${NETWORK_MODE:-bridge}'

  horizon:
    depends_on:
      - postgres
      - core
    build:
      # set build context to the root directory of the go monorepo
      context: /my-project/path/
      dockerfile: ./horizon/docker/Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://x:x@host.docker.internal:5432/horizon?sslmode=disable
      - STELLAR_CORE_DATABASE_URL=postgres://x:x@host.docker.internal:5432/stellar?sslmode=disable
      # to connect to the public stellar network
      # - NETWORK_PASSPHRASE=Public Global Stellar Network ; September 2015
      - NETWORK_PASSPHRASE=Test SDF Network ; September 2015
      - STELLAR_CORE_URL=http://host.docker.internal:11626
      - INGEST=true
    network_mode: '${NETWORK_MODE:-bridge}'
    command: ["--apply-migrations"]
```

stellar-core-testnet.env

```
DATABASE=postgresql://user=spotii password=spotii host=host.docker.internal port=5432 dbname=stellar

compat_minimal_POSTGRES_PORT=5432
compat_minimal_PEER_PORT=11625
compat_minimal_HTTP_PORT=11626
compat_minimal_PEER_SEED=SBTEQJMDYCNRXRBEUUK7PTC737GVE24VSFVEHQXRALAARQCU5O246KVT
compat_minimal_VALIDATION_SEED=SACTBO4KQ3LYYRRKBST3ZCO24FYRDP2CYN3W5IPP2OTC3NUIKFGZSRRY

PREFERRED_PEERS=["core-testnet1.stellar.org", "core-testnet2.stellar.org", "core-testnet3.stellar.org"]

UNSAFE_QUORUM=true
FAILURE_SAFETY=0

VALIDATORS=["GDKXE2OZMJIPOSLNA6N6F2BVCI3O777I2OOC4BV7VOYUEHYX7RTRYA7Y", "GCUCJTIYXSOXKBSNFGNFWW5MUQ54HKRPGJUTQFJ5RQXZXNOLNXYDHRAP", "GC2V2EFSXN6SQTWVYA5EPJPBWWIMSD2XQNKUOHGEKB535AQE2I6IXV2Z"]

HISTORY_PEERS=["core_testnet_001", "core_testnet_002", "core_testnet_003"]

HISTORY_GET=wget -q -O {1} https://history.stellar.org/prd/core-testnet/%s/{0}

NETWORK_PASSPHRASE=Test SDF Network ; September 2015
```
